// ─── Player types ───

import type { AvatarId, MediaId } from './account';

/** Unique player id (generated by the server) */
export type PlayerId = string;

/** Seat position */
export type Seat = 'N' | 'E' | 'S' | 'W';

/** Player color (hex code) */
export type PlayerColor = string;

/** Player info */
export interface PlayerInfo {
  readonly id: PlayerId;
  readonly username: string;
  readonly nickname: string;
  readonly color: PlayerColor;
  readonly avatar: AvatarId;
  readonly avatarImage: MediaId | null;
  readonly isBot?: boolean;
}

/** Player connection status */
export type ConnectionStatus = 'connected' | 'disconnected';
